var define,require;(function(r,j){r.mfeng==j&&(r.mfeng={});var d={};define=function(b,f){if(d[b])throw Error("module "+b+" already defined!");d[b]={id:b,factory:f}};require=function(b){var f=d[b];if(!f)throw Error("module "+b+" not found!");f.factory&&(b=f.factory,f.exports={},delete f.factory,b(require,f.exports,f));return f.exports}})(window);
define("util",function(r,j){var d={toString:function(b){return Object.prototype.toString.call(b)},isFunction:function(b){return b&&"[object Function]"===d.toString(b)},isPlainObject:function(b){return b&&"[object Object]"===d.toString(b)},isArray:function(b){return d.isFunction(Array.isArray)?Array.isArray(b):b&&"[object Array]"===d.toString(b)},mix:function(b,f,c){c=!1===c?!1:!0;var k,g,h;for(k in f)h=f[k],g=b[k],c&&(d.isArray(h)||d.isPlainObject(h))?(g=b[k]=g&&(d.isArray(g)||d.isPlainObject(g))?
g:d.isArray(g)?[]:{},d.mix(g,h,c)):b[k]=h;return b},clone:function(b){return d.mix({},b)},apply:function(b,f,c){c&&d.apply(b,c);return d.mix(b,f)},bind:function(){var b=arguments[0],f=arguments[1],c=Array.prototype.splice.call(arguments,2);return function(){return f.apply(b,c.concat(Array.prototype.slice.call(arguments)))}},addClass:function(b,f){var c=b.className.split(" ");if(-1<c.indexOf(f))return!1;c.push(f);b.className=c.join(" ")},removeClass:function(b,f){var c=b.className.split(" "),d=c.indexOf(f);
if(-1>=d)return!1;c.splice(d,1);b.className=c.join(" ")},hasClass:function(b,f){return-1<(" "+b.className+" ").replace(/[\t\r\n]/g," ").indexOf(" "+f+" ")?!0:!1},observe:function(b){b.__listeners={};b.on=function(b,c,d){void 0===this.__listeners[b]&&(this.__listeners[b]=[]);this.__listeners[b].push({eventName:b,handler:c,host:d||this})};b.fire=function(b){if(void 0===this.__listeners[b])return!1;var c=this.__listeners[b],d,g=0,h=this.__listeners[b].length,j=Array.prototype.slice.call(arguments,1);
for(j.unshift(b);g<h;g++)d=c[g],d.handler.apply(d.host,j)}}};d.mix(j,d)});
define("widget",function(r,j){function d(a,b,c){a.style[q]="opera"===u?"translate("+b+"px, "+c+"px)":"translate3d("+b+"px, "+c+"px, 0)"}function b(){return{x:document.body.scrollLeft,y:document.body.scrollTop}}function f(a,b,c,d,e){if(void 0===a)throw"parameter el must be give!";a.style[l]=(void 0===b?"all":b)+" "+(void 0===c?250:c)+"ms "+(void 0===d?"ease":d)+" "+(void 0===e?0:e)+"ms";if("webkit"===u||"moz"===u)a.style[v]="preserve-3d",a.style[w]="1",a.style[x]="hidden"}function c(){this.init.apply(this,
arguments)}function k(a,b,c,d){e.observe(this);this._el=document.getElementById(a);this._size=b;this._activeClassName=c;this._items=Array.prototype.slice.call(this._el.children);!0===d&&this._el.addEventListener("click",e.bind(this,this.clickHandler),!1)}function g(a){e.observe(this);if(!a||!a.id)throw Error("id is required!");e.apply(this,a||{},g.DEFAULT_CONFIG);this._el=document.getElementById(this.id);this._btnClose=this._el.getElementsByClassName(this.closeBtnClass)[0];this._wrapper=this._el.getElementsByClassName(this.wrapperClass)[0];
this._transitionLock=!1;a=e.bind(this,this._scrollHandler);window.addEventListener("scroll",a,!1);a=e.bind(this,this._wrapperClkHandler);this._wrapper.addEventListener("click",a,!1);a=e.bind(this,this._closeClkHandler);this._btnClose.addEventListener("click",a,!1);this._init();this._listener();this._applyStyle()}function h(){this._init.apply(this,arguments)}function s(){this._init.apply(this,arguments)}var e=r("util"),l,q,n,m,p,w,v,x,t=document.body.style,u=void 0!==t.webkitTransition&&"webkit"||
void 0!==t.MozTransition&&"moz"||void 0!==t.OTransition&&"opera"||void 0!==t.transition&&"orign"||void 0!==t.msTransform&&"ms";switch(u){case "orign":l="transition";q=n="transform";m="transitionDuration";p="transitionEnd";break;default:l="webkitTransition";q="webkitTransform";n="-webkit-transform";m="webkitTransitionDuration";p="webkitTransitionEnd";w="webkitPerspective";v="webkitTransformStyle";x="webkitBackfaceVisibility";break;case "moz":l="MozTransition";q="MozTransform";n="-moz-transform";m=
"MozTransitionDuration";p="transitionend";w="MozPerspective";v="MozTransformStyle";x="MozBackfaceVisibility";break;case "opera":l="OTransition";q="OTransform";n="-o-transform";m="OTransitionDuration";p="oTransitionEnd";break;case "ms":l="MSTransition",q="msTransform",n="-ms-transform",m="MSTransitionDuration",p="msTransitionEnd"}c.DEFAULT_CONFIG={direction:"horizontal",isAutoPlay:!1,isCircularly:!1,defaultPageIndex:0,showPageNumber:1,speed:400,interval:3E3};c.MIN_MOVEMENT=30;c.status={TOUCH:"__touch__",
TOUCH_END:"__touchend__",SLIDING:"__sliding__",FIRST_BLOCK:1,SECOND_BLOCK:2};c.prototype={init:function(a){if(!a||!a.id)throw Error("id is required!");e.apply(this,a||{},c.DEFAULT_CONFIG);this._el=document.getElementById(this.id);this._content=this._el.innerHTML;this._pages=Array.prototype.slice.call(this._el.children).length;this._currentPage=this.defaultPageIndex;this._initDom();this._applyStyle();this._bindEvent();if(this.indicator){e.apply(this.indicator,{size:this._pages});a=k.create(this.indicator);
var b=this,d=function(a,c){b.isAutoPlay&&b.replay();b.pageTo(c)};if(!0===this.indicator.controllable)a.on("change",d);this.setIndicator(a)}this._initStatus();this.isAutoPlay&&this.play()},_initDom:function(){this._wrapper=document.createElement("div");this.isCircularly?(this._wrapper=document.createElement("div"),this._firstBlock=c.status.FIRST_BLOCK,this._secondBlock=c.status.SECOND_BLOCK,this._wrapper.innerHTML=this._content+this._content):(this._wrapper.innerHTML=this._content,this._firstBlock=
this._secondBlock=null);this._el.innerHTML="";this._el.appendChild(this._wrapper)},_applyStyle:function(){var a=this.pageWidth*this._pages,b=this.isCircularly?2:1;this._el.style.overflow="hidden";if("horizontal"===this.direction){this._wrapper.style.width=2*a+"px";for(var a=Array.prototype.slice.call(this._wrapper.children),b=a.length,c=0;c<b;c++)a[c].style.width=this.pageWidth+"px"}else this._wrapper.style.width="100%",this._wrapper.style.height=b*a+"px";f(this._wrapper,n,this.speed)},_initStatus:function(){this.isCircularly?
(this._frames=2*this._pages,this._activeBlock=this._secondBlock,this.isLastFrame()&&this._switchBlock()):this._frames=this._pages;this._isPageLock=this._isTouchLock=!1;this.resetTo(this.defaultPageIndex);this._indicator&&this._indicator.active(this._currentPage)},isFirstPage:function(){return 0===this._currentPage},isLastPage:function(){return this._currentPage===this._pages-1},isFirstFrame:function(){return this._getFrame(this._currentPage)===Math.floor(this.showPageNumber/2)},isLastFrame:function(){return this._getFrame(this._currentPage)===
this._frames-Math.ceil(this.showPageNumber/2)},next:function(){if(this._isPageLock)return!1;var a=this._currentPage;this.isLastPage()?!0===this.isCircularly&&(this._switchBlock(),a=0):a++;this._isPageLock=!0;this.pageTo(a)},prev:function(){if(this._isPageLock)return!1;var a=this._currentPage;this.isFirstPage()?!0===this.isCircularly&&(this._switchBlock(),a=this._pages-1):a--;this._isPageLock=!0;this.pageTo(a)},_switchBlock:function(){this.isCircularly&&(this._activeBlock=this._isFirstBlock()?this._secondBlock:
this._firstBlock)},_isFirstBlock:function(){return this._activeBlock===this._firstBlock},play:function(){if(this._intervalId)return!1;this._intervalId=setInterval(e.bind(this,this.next),this.interval)},stop:function(){if(!this._intervalId)return!1;clearInterval(this._intervalId);delete this._intervalId},replay:function(){this.stop();this.play()},refresh:function(a){e.apply(this,a);this._applyStyle();if(this.isCircularly){if(this._activeBlock=this._secondBlock,this._currentFrame=this._getFrame(this._currentPage),
this._currentFrame<=Math.floor(this.showPageNumber/2)||this._currentFrame>=this._frames-Math.ceil(this.showPageNumber/2))this._switchBlock(),this.resetTo(this._currentPage)}else this.resetTo(this._currentPage)},pageTo:function(a){this._currentPage!==a&&(this._isTouchLock=!0);this._currentPage=a;this._currentFrame=this._getFrame(a);this._move(-(this._currentFrame*this.pageWidth))},resetTo:function(a){this._wrapper.style[l]=null;this._wrapper.style[m]=0;this.pageTo(a);var b=this;setTimeout(function(){b._wrapper.style[m]=
b.speed+"ms";b._isPageLock=!1},10)},setIndicator:function(a){this._indicator=a},_getFrame:function(a){return this.isCircularly?this._isFirstBlock()?a:a+this._pages:a},_move:function(a){d(this._wrapper,a,0)},_bindEvent:function(){var a="ontouchmove"in window?"touchmove":"mousemove",b="ontouchend"in window?"touchend":"mouseup";this._el.addEventListener("ontouchstart"in window?"touchstart":"mousedown",e.bind(this,this._touchstartHandler),!1);this._el.addEventListener(a,e.bind(this,this._touchmoveHandler),
!1);this._el.addEventListener(b,e.bind(this,this._touchendHandler),!1);this._wrapper.addEventListener(p,e.bind(this,this._transitionEndHandler),!1)},_touchstartHandler:function(a){if(!0===this._isTouchLock)return!1;this._status=c.status.TOUCH;this.isAutoPlay&&this.stop();this._startX=this._endX=a.touches?a.touches[0].clientX:a.clientX;this._startY=this._endY=a.touches?a.touches[0].clientY:a.clientY;this._moveStartTime=a.timeStamp||Date.now()},_touchmoveHandler:function(a){if(this._status!=c.status.TOUCH)return!1;
var b=a.touches?a.touches[0].clientX:a.clientX,d=b-this._startX;this._endX=b;this._endY=a.touches?a.touches[0].clientY:a.clientY;if(Math.abs(this._endY-this._startY)>Math.abs(this._endX-this._startX))return this._endX=this._startX,!1;if(!0!==this.isCircularly&&(this.isFirstPage()&&0<d||this.isLastPage()&&0>d))return!1;this._wrapper.style[l]=null;this._wrapper.style[m]=0;this._move(1.2*d-this._currentFrame*this.pageWidth);a.preventDefault()},_touchendHandler:function(a){var b;b=this._endX-this._startX;
a=(a.timeStamp||Date.now())-this._moveStartTime;a=400>a?a/Math.abs(b)*(this.pageWidth-Math.abs(b)):this.speed;if(this._status!=c.status.TOUCH)return!1;this._status=c.status.TOUCH_END;this.isAutoPlay&&this.play();this._wrapper.style[l]=n+" "+a+"ms";Math.abs(b)>c.MIN_MOVEMENT?(this._isPageLock=!1,0<b?this.prev():this.next()):(this._isPageLock=!0,this.pageTo(this._currentPage))},_transitionEndHandler:function(){this._wrapper.style[m]=this.speed+"ms";!0!==this.isCircularly&&!0===this.isAutoPlay&&(this.isFirstPage()?
this.play():this.isLastPage()&&this.stop());this._isPageLock=this._isTouchLock=!1;this.isCircularly&&(this.isFirstFrame()?this._reachFirstFrame():this.isLastFrame()&&this._reachLastFrame());this._indicator&&this._indicator.active(this._currentPage)},_reachFirstFrame:function(){this._switchBlock();this.resetTo(this._currentPage)},_reachLastFrame:function(){this._switchBlock();this.resetTo(this._currentPage)}};k.create=function(a){return new k(a.id,a.size,a.activeClassName||"active",a.controllable)};
k.prototype={active:function(a){this._activeItem&&e.removeClass(this._activeItem,this._activeClassName);this._activeItem=this._items[a];e.addClass(this._activeItem,this._activeClassName)},clickHandler:function(a){a=this._items.indexOf(a.target);-1<a&&this.fire("change",a)}};j.Slide=c;g.DEFAULT_CONFIG={isFixed:!0,isAutoPlay:!1,hasScrollTransition:!1,isInitActive:!1,useTransition:!0,activedStopTime:1E3,animateDuation:1E3,animateFunciton:"ease-in-out",animateProperty:"height",toggleClass:"active",
closeBtnClass:"btnClose",wrapperClass:"wrapper",onStart:function(){},onScroll:function(){},onWrapperClk:function(){},onClose:function(){},onActive:function(){},onPassive:function(){}};g.prototype={_init:function(){this._initTop=this._el.offsetTop;this.onStart();this._isActive=this.isInitActive;this._transitionLock=!1},_applyStyle:function(){this.useTransition&&f(this._wrapper,this.animateProperty,this.animateDuation,this.animateFunciton);this.isAutoPlay&&!this.isAutoPlayDone&&(this.wrapperToggle(),
this.useTransition&&(this._transitionLock=!0),this.isAutoPlayDone=!1);if(this.isFixed&&this.hasScrollTransition){new s;var a=e.bind(this,this._scrollEndHandler);window.addEventListener("scrollend",a,!1)}},_listener:function(){var a=e.bind(this,this._transitionEndHandler);this._wrapper.addEventListener(p,a,!1)},_scrollHandler:function(){this.isFixed&&(this.hasScrollTransition||d(this._el,0,b().y));this.onScroll()},_scrollEndHandler:function(){this.isFixed&&this.hasScrollTransition&&(f(this._el,n,500),
d(this._el,0,b().y))},_wrapperClkHandler:function(a){if(this.useTransition&&this._transitionLock)return!1;this.onWrapperClk(a);a.preventDefault()},_closeClkHandler:function(a){a.preventDefault();this._el.style.display="none";this.onClose(this._el)},refresh:function(a){e.apply(this,a);this._applyStyle()},getEl:function(){return this._el},getWrapper:function(){return this._wrapper},getCloseBtn:function(){return this._btnClose},replaceToClass:function(a){return this._el.className=a},wrapperToggle:function(){this.useTransition&&
(this._transitionLock=!0);e.hasClass(this._el,this.toggleClass)?e.removeClass(this._el,this.toggleClass):e.addClass(this._el,this.toggleClass)},isActive:function(){return this._isActive},setActive:function(a){this._isActive=a},isTransitionLock:function(){return this._transitionLock},hasAutoPlayed:function(){return this.isAutoPlayDone},_transitionEndHandler:function(){this.isAutoPlay&&!this.isAutoPlayDone&&e.hasClass(this._el,this.toggleClass)?setTimeout(e.bind(this,this.wrapperToggle),this.activedStopTime):
this.isAutoPlay&&(!this.isAutoPlayDone&&!e.hasClass(this._el,this.toggleClass))&&(this.isAutoPlayDone=!0);this._isActive=this._isActive?!1:!0;e.hasClass(this._el,this.toggleClass)&&this.onActive();!e.hasClass(this._el,this.toggleClass)&&this.onPassive();this.useTransition&&(this._transitionLock=!1)}};j.AdBlock=g;h.DEFAULT_CONFIG={maxRetyrTimes:10,interval:200,callback:null};h.prototype={_init:function(a){e.apply(this,a||{},h.DEFAULT_CONFIG);this._docWidth=a.clientWidth||document.body.clientWidth;
this._retryTimes=0;this._start()},_start:function(){var a=this;setTimeout(function(){a._detect()},this.interval)},_detect:function(){var a=this;if(this._retryTimes<this.maxRetyrTimes)if(this._retryTimes++,this._docWidth!=document.body.clientWidth)if(this.callback)this.callback();else{var b=document.createEvent("Event");b.initEvent("deviceready",!1,!0);window.dispatchEvent(b)}else setTimeout(function(){a._detect()},this.interval)}};j.OrientationReadyDetector=h;s.DEFAULT_CONFIG={timeout:250};s.prototype=
{_init:function(a){e.apply(this,a||{},s.DEFAULT_CONFIG);a=e.bind(this,this._detect);window.addEventListener("scroll",a,!1);this._timer=null;this._detect()},_detect:function(){var a=this,c=0,d=b().y;this._timer=setTimeout(function(){c=b().y;if(c===d){var e=document.createEvent("Event");e.initEvent("scrollend",!1,!0);window.dispatchEvent(e);clearTimeout(a._timer)}},this.timeout)}};j.ScrollEndDetector=s});
